#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2019-present Team LibreELEC (https://libreelec.tv)

. config/options "${1}"

(
  flock --exclusive 95

  count=$(< "${THREAD_CONTROL}/counts/${PKG_NAME}.count")
  count=$((count - 1))
  echo ${count} >"${THREAD_CONTROL}/counts/${PKG_NAME}.count"

  if [ ${count} -eq 0 ]; then
    if [ -d "${PKG_BUILD}" -a "${PKG_SECTION}" != "virtual" ]; then
      print_color CLR_AUTOREMOVE "AUTOREMOVE ${PKG_BUILD}\n"
      rm -r "${PKG_BUILD}"
    fi
  elif [ ${count} -lt 0 ]; then
    die "ERROR: negative reference count for ${PKG_NAME}"
  fi
) 95>"${THREAD_CONTROL}/locks/${PKG_NAME}.autoremove"

# reference count any associated packages
if [ -n "${PKG_DEPENDS_UNPACK}" ]; then
  for pkgname in ${PKG_DEPENDS_UNPACK}; do
    ${SCRIPTS}/autoremove "${pkgname}"
  done
fi
